load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "portability",
    hdrs = ["include/aifocore/platform/portability.h"],
    strip_include_prefix = "include",
    visibility = ["//visibility:public"],
)

cc_library(
    name = "concepts",
    hdrs = ["include/aifocore/concepts/numeric.h"],
    strip_include_prefix = "include",
    visibility = ["//aifo:__subpackages__"],
    deps = [
        "@cereal",
        "@fmt",
    ],
)

cc_library(
    name = "math",
    hdrs = ["include/aifocore/concepts/math.h"],
    strip_include_prefix = "include",
    visibility = ["//aifo:__subpackages__"],
)

cc_library(
    name = "ndarray",
    hdrs = [
        "include/aifocore/math/ndarray.h",
        "include/aifocore/math/ndarray_all.h",
        "include/aifocore/math/ndarray_functions.h",
        "include/aifocore/math/ndarray_operators.h",
    ],
    strip_include_prefix = "include",
    visibility = ["//visibility:public"],
)

cc_library(
    name = "result",
    hdrs = [
        "include/aifocore/status/result.h",
    ],
    strip_include_prefix = "include",
    visibility = ["//visibility:public"],
)

cc_binary(
    name = "trace_example",
    srcs = ["src/status/trace_example.cpp"],
    deps = [
        ":status",
        "@abseil-cpp//absl/status:status",
        "@abseil-cpp//absl/status:statusor",
    ],
)

cc_library(
    name = "tiling_python",
    hdrs = ["include/aifocore/tiling/python/grid_wrapper.h"],
    strip_include_prefix = "include",
    visibility = ["//visibility:public"],
)

cc_library(
    name = "bs_thread_pool",
    hdrs = ["include/aifocore/utilities/bs_thread_pool.h"],
    strip_include_prefix = "include",
    visibility = ["//visibility:public"],
)

cc_library(
    name = "treiber_stack",
    hdrs = ["include/aifocore/utilities/treiber_stack.h"],
    strip_include_prefix = "include",
    visibility = ["//visibility:public"],
)

cc_library(
    name = "thread_pool_singleton",
    srcs = ["src/utilities/thread_pool_singleton.cpp"],
    hdrs = ["include/aifocore/utilities/thread_pool_singleton.h"],
    strip_include_prefix = "include",
    visibility = ["//visibility:public"],
    deps = [
        ":bs_thread_pool",
    ],
)

cc_library(
    name = "utilities-fmt",
    hdrs = ["include/aifocore/utilities/fmt.h"],
    strip_include_prefix = "include",
    visibility = ["//visibility:public"],
    deps = ["@fmt"],
)

cc_library(
    name = "utilities-core",
    hdrs = [
        "include/aifocore/utilities/spinners.h",
        "include/aifocore/utilities/temporary.h",
    ],
    strip_include_prefix = "include",
    visibility = ["//visibility:public"],
    deps = [
        ":utilities-fmt",
    ],
)

cc_library(
    name = "utilities",
    hdrs = [
        "include/aifocore/utilities/spinners.h",
        "include/aifocore/utilities/temporary.h",
    ],
    strip_include_prefix = "include",
    visibility = ["//visibility:public"],
    deps = [
        ":status",
        ":utilities-fmt",
        ":utilities-vips",
        ":utilities-zip",
    ],
)
