load("@pybind11_bazel//:build_defs.bzl", "pybind_extension")

package(default_visibility = ["//visibility:public"])

pybind_extension(
    name = "inference_engine_module",
    srcs = [
        "inference_engine_module.cpp",
    ],
    copts = [
        "-std=c++20",
        "-DPYBIND11_CPP17",
        "-DPYBIND11_HAS_FILESYSTEM",
    ],
    deps = [
        "//aifo/ahcore:inference_engine",
        "@abseil-cpp//absl/status:status",
    ],
)

cc_binary(
    name = "inference",
    srcs = [
        "inference.cpp",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//aifo/ahcore:inference_engine",
        "//third_party/CLI11",
        "@abseil-cpp//absl/status:status",
        "@spdlog",
    ],
)
