// Copyright 2025 Jonas Teuwen. All rights reserved.
//
// FastSlide WASM Worker - Handles WASM module loading and tile processing

// Import the WASM module (will be generated by build)
import createFastSlideModule from "../fastslide_multiplex.js";

let module = null;
let FS = null;
let reader = null;
let tileCache = new Map(); // Cache tiles to avoid re-reading

// Initialize WASM module
async function initializeModule() {
  try {
    module = await createFastSlideModule();
    FS = module.FS;

    if (!FS || !module.WORKERFS) {
      throw new Error("FS or WORKERFS not exported from WASM module");
    }

    // Send ready message
    self.postMessage({
      type: "ready",
      message: "WASM module loaded successfully",
    });
  } catch (err) {
    console.error("Failed to initialize WASM module:", err);
    self.postMessage({
      type: "error",
      message: "Failed to load WASM module: " + err.message,
    });
  }
}

// Handle messages from main thread
self.onmessage = async function (e) {
  const { type, data } = e.data;

  try {
    switch (type) {
      case "loadFile":
        await handleLoadFile(data);
        break;

      case "getInfo":
        handleGetInfo();
        break;

      case "readTile":
        await handleReadTile(data);
        break;

      case "readRegion":
        await handleReadRegion(data);
        break;

      default:
        console.warn("Unknown message type:", type);
    }
  } catch (err) {
    console.error("Error handling message:", type, err);
    self.postMessage({
      type: "error",
      message: `Error in ${type}: ${err.message}`,
    });
  }
};

// Load and mount file using WORKERFS
async function handleLoadFile(data) {
  const { file } = data;

  if (!module || !FS) {
    throw new Error("WASM module not initialized");
  }

  const startTime = performance.now();

  try {
    // Clean up previous mount if exists
    if (reader) {
      reader = null;
      tileCache.clear();
    }

    try {
      FS.unmount("/work");
    } catch (e) {
      // Ignore if not mounted
    }

    // Create mount point
    try {
      FS.mkdir("/work");
    } catch (e) {
      // Directory might already exist
    }

    // Mount file using WORKERFS (enables lazy loading)
    FS.mount(module.WORKERFS, { files: [file] }, "/work");

    const virtualPath = "/work/" + file.name;

    // Check if file is accessible
    const fileInfo = FS.analyzePath(virtualPath);
    if (!fileInfo.exists) {
      throw new Error("File not found in virtual filesystem");
    }

    // Open slide with FastSlide
    reader = module.FastSlideReader.fromFilePath(virtualPath);

    const parseTime = performance.now() - startTime;

    // Get slide information
    const numLevels = reader.numLevels;
    const dimensions = reader.dimensions;
    const format = reader.format;
    const mpp = reader.mpp;

    // Get level info for all levels
    const levelInfo = [];
    for (let i = 0; i < numLevels; i++) {
      const info = reader.getLevelInfo(i);
      levelInfo.push({
        level: i,
        width: info.width,
        height: info.height,
        downsampleFactor: info.downsampleFactor,
      });
    }

    self.postMessage({
      type: "slideLoaded",
      data: {
        numLevels,
        dimensions,
        format,
        mpp,
        levelInfo,
        fileName: file.name,
        fileSize: file.size,
        parseTime,
      },
    });
  } catch (err) {
    console.error("Failed to load file:", err);
    throw new Error("Failed to open slide: " + err.message);
  }
}

// Get slide information
function handleGetInfo() {
  if (!reader) {
    throw new Error("No slide loaded");
  }

  const numLevels = reader.numLevels;
  const dimensions = reader.dimensions;
  const format = reader.format;

  const levelInfo = [];
  for (let i = 0; i < numLevels; i++) {
    const info = reader.getLevelInfo(i);
    levelInfo.push({
      level: i,
      width: info.width,
      height: info.height,
      downsampleFactor: info.downsampleFactor,
    });
  }

  self.postMessage({
    type: "slideInfo",
    data: {
      numLevels,
      dimensions,
      format,
      levelInfo,
    },
  });
}

// Read a tile region from the slide
async function handleReadTile(data) {
  const { level, x, y, width, height, tileId } = data;

  if (!reader) {
    throw new Error("No slide loaded");
  }

  console.log(
    `[Worker] Reading tile: ${tileId} (level ${level}, ${x},${y} ${width}x${height})`
  );

  // Check cache
  const cacheKey = `${level}:${x}:${y}:${width}:${height}`;
  if (tileCache.has(cacheKey)) {
    console.log(`[Worker] Cache hit for ${tileId}`);
    const cached = tileCache.get(cacheKey);
    self.postMessage(
      {
        type: "tileData",
        data: {
          ...cached,
          tileId,
          fromCache: true,
        },
      },
      [cached.data.buffer]
    );
    return;
  }

  const startTime = performance.now();

  try {
    // Read region from slide
    const image = reader.readRegion(x, y, width, height, level);

    const readTime = performance.now() - startTime;

    // Get image data as typed array
    const imageData = image.data;
    const imageWidth = image.width;
    const imageHeight = image.height;
    const channels = image.channels;

    console.log(
      `[Worker] Read success: ${tileId}, size: ${imageWidth}x${imageHeight}x${channels}, bytes: ${imageData.byteLength}`
    );

    // Convert to Uint8Array for transfer
    let dataArray;
    if (imageData instanceof Uint8Array) {
      dataArray = imageData;
    } else {
      // Convert other types to Uint8Array
      dataArray = new Uint8Array(imageData.buffer);
    }

    const result = {
      tileId,
      level,
      x,
      y,
      width: imageWidth,
      height: imageHeight,
      channels,
      data: dataArray,
      readTime,
      fromCache: false,
    };

    // Cache the tile (limit cache size)
    if (tileCache.size < 100) {
      tileCache.set(cacheKey, {
        level,
        x,
        y,
        width: imageWidth,
        height: imageHeight,
        channels,
        data: new Uint8Array(dataArray), // Clone for cache
        readTime,
      });
    }

    // Send result with transferable
    self.postMessage(
      {
        type: "tileData",
        data: result,
      },
      [dataArray.buffer]
    );
  } catch (err) {
    console.error("Failed to read tile:", err);
    throw new Error("Failed to read tile: " + err.message);
  }
}

// Read arbitrary region from the slide
async function handleReadRegion(data) {
  const { level, x, y, width, height } = data;

  if (!reader) {
    throw new Error("No slide loaded");
  }

  const startTime = performance.now();

  try {
    const image = reader.readRegion(x, y, width, height, level);
    const readTime = performance.now() - startTime;

    const imageData = image.data;
    const imageWidth = image.width;
    const imageHeight = image.height;
    const channels = image.channels;

    // Convert to Uint8Array for transfer
    let dataArray;
    if (imageData instanceof Uint8Array) {
      dataArray = imageData;
    } else {
      dataArray = new Uint8Array(imageData.buffer);
    }

    self.postMessage(
      {
        type: "regionData",
        data: {
          level,
          x,
          y,
          width: imageWidth,
          height: imageHeight,
          channels,
          data: dataArray,
          readTime,
        },
      },
      [dataArray.buffer]
    );
  } catch (err) {
    console.error("Failed to read region:", err);
    throw new Error("Failed to read region: " + err.message);
  }
}

// Start initialization
initializeModule();
